name: aviatoruz
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  lottie: ^3.1.3
  iconly: ^1.0.1
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.3.3
  file_picker: ^8.0.3
  image_picker: ^1.1.1
  firebase_database: ^11.1.4
  shared_preferences: ^2.2.3
  firebase_app_check: ^0.3.1+3
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.3
  dash_chat_2: ^0.0.20
  photo_view: ^0.15.0
  url_launcher: ^6.2.6
  share_plus: ^10.1.0
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
  dart_code_metrics: ^4.19.2
  flutter_screenutil: ^5.9.3
  open_file: ^3.5.8
  text_scroll: ^0.2.0
  youtube_player_flutter: ^9.1.1

  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/aviatoruz_logo.png"       


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
